module.exports = [
//	Chunk label			Tags (order is relevant)
	["NP",				['NNP', 'CD', 'NNS']],
	["NP",				['DT', 'PRP$', 'JJ', 'JJS', '$', 'CD', '$', 'NN', 'NNS']],
	["NP",				['DT', 'PRP$', 'JJ', 'JJS', '$', 'CD', '$', 'NNP', 'NNPS']],
	["VP",				['MD', 'VBP', 'VB']],
	["VP",				['MD', 'VBD']],
	["VP",				['MD', 'VB']],
	["VP",				['VBZ', 'VBG']],
	["NP",				['NNP', 'NNPS']],
	["ADV",				['RB', 'RB']],
	["ADJP",			['RB', 'JJ']],
	["PP",				'IN'],
	["PRT",				'RP'],
	["NP",				'PRP'],
	["NP",				'NNP'],
	["NP",				'NNPS'],
	["NP",				'NN'],
	["NP",				'DT'],
	["ADJ",				'JJ'],
	["NP",				'NNS'],
	["VAUX",			['VB', 'RB']],
	["VAUX",			['VBP', 'RB']],
	["VP",				'VBZ'],
	["VP",				'VBP'],
	["VP",				'VBD'],
	["ADV",				'WRB'],
	["ADV",				'RB'],
	["PUNCT",			'.'],
	["PUNCT",			','],
	["SP",				['PP', 'NP']],
	["NP",				["NP","NN","POS"]],
	["NP",				["NP","NNP","POS"]],
	["NP",				["NP","NNS","POS"]],
	["NP",				["NP","NNPS","POS"]],
];