module.exports = [
//	Chunk label			Tags (order is relevant)
	["NP",				['NNP', 'CD', 'NNS']],
	["NP",				['DT', 'PRP$', 'JJ', 'JJS', "JJR", '$', 'CD', '$', 'NN', 'NNS']],
	["NP",				['DT', 'PRP$', 'JJ', 'JJS', "JJR", '$', 'CD', '$', 'NNP', 'NNPS']],
	["VP",				['MD', 'VBP', 'VB']],
	["VP",				['MD', 'VBD']],
	["VP",				['MD', 'VB']],
	["VP",				['VBZ', 'VBG']],
	["NP",				['NNP', 'NNPS']],
	["ADV",				['RB', 'RB']],
	["ADJP",			['RB', 'JJ']],
	["PP",				'IN'],
	["PP",				["NP","CD","NN","NNS","IN","PP"],(L,R,i)=>~L.tags.indexOf("CD")||~R.tags.indexOf("CD")],
	["PRT",				'RP'],
	["NP",				'PRP'],
	["NP",				'NNP'],
	["NP",				'NNPS'],
	["NP",				'NN'],
	["UH",				["DT",","],					(L,R,i,ns)=>L.index[0]===0&&R.index[1]===1], // in some cases a conditional function is required
	["NP",				'DT'],
	["ADJ",				'JJ'],
	["NP",				'NNS'],
	["VAUX",			['VB', 'RB']],
	["VP",				'VBZ'],
	["VP",				'VBP'],
	["VP",				'VBD'],
	["VP",				'VBG'],
	["ADV",				'WRB'],
	["ADV",				'RB'],
	["PUNCT",			'.'],
	["PUNCT",			','],
	["SP",				['PP', 'NP']],
	["NP",				["NP","POS","NN"]],
];