module.exports = [
// 	left type		Right type		Direction 	Label		repair condition
	["NP",			"CC",			"<-",		"NP"		],
	["CC",			"NP",			"->",		"NP"		],
	["NP",			"PUNCT",		"<-",		"NP"		],
	["PUNCT",		"NP",			"->",		"NP"		],
	['NP', 			'VP', 			"->", 		'NSUBJ'		],
	['VP', 			'NP', 			"<-", 		'DOBJ'		],
	['VB', 			'NP', 			"<-", 		'DOBJ'		],
	['PP', 			'NP', 			"<-", 		'POBJ'		],
	['NP', 			'PP', 			"<-", 		'PREP'		],
	['VP', 			'PP', 			"<-", 		'PREP'		],
	['VB', 			'PP', 			"<-", 		'PREP'		],
	['VBN', 		'PP', 			"<-", 		'AGENT'		],
	['VP', 			'VP', 			"<-", 		'CCOMP'		],
	['VP', 			'ADV', 			"<-", 		'ADVMOD'	],
	['VB', 			'ADV', 			"<-", 		'ADVMOD'	],
	['ADV', 		'PP', 			"<-", 		'PREP'		],
	['PP', 			'VP', 			"->", 		'PREP'		],
	['VP', 			'ADJ', 			"<-", 		'ACOMP'		],
	['VB', 			'ADJ', 			"<-", 		'ACOMP'		],
	['VP', 			'ADJP', 		"<-", 		'ACOMP'		],
	['VB', 			'ADJP', 		"<-", 		'ACOMP'		],
	['VB', 			'VP', 			"->", 		'AUX'		],
	['VP', 			'VB', 			"->", 		'AUX'		],
	['VAUX', 		'VP', 			"->", 		'AUX'		],
	['VAUX', 		'VB', 			"->", 		'AUX'		],
	["VP",			"VBN",			"->",		"AUXPASS"	],
	["VB",			"VBN",			"->",		"AUXPASS"	],
	["NP",			"VBN",			"->",		"NSUBJPASS"	],
	['VP', 			'PUNCT', 		"<-", 		'PUNCT', 	1], // one repair
	['VB', 			'PUNCT', 		"<-", 		'PUNCT', 	1],
	['VBN', 		'PUNCT', 		"<-", 		'PUNCT', 	1],
	['PUNCT', 		'VP', 			"->", 		'PUNCT', 	1],
	['PUNCT', 		'VB', 			"->", 		'PUNCT', 	1],
	['PUNCT', 		'VBN', 			"->", 		'PUNCT', 	1],
	['ADV', 		'VP', 			"->", 		'ADVMOD', 	2], // two repairs
	['ADV', 		'VB', 			"->", 		'ADVMOD', 	2],
	['ADV', 		'ADV', 			"->", 		'ADVMOD', 	2],
	["UH",			"VP",			"->",		"INTERJ",	 ],
	["VBG",			"PP",			"<-",		"PREP"		 ],
	["VBG",			"VB",			"->",		"ADVCL",	2],
	["TO",			"NP",			"<-",		"POBJ"		 ],
	["VB",			"TO",			"<-",		"DATIVE"	 ],
	["TO",			"VB",			"->",		"AUX"	 	 ],
	["VBN",			"NP",			"<-",		"ATTR"		 ],
	["VBN",			"VB",			"<-",		"XCOMP"	 	 ],
	["VBN",			"VP",			"<-",		"XCOMP"	 	 ],
	["MD",			"VP",			"->",		"AUX"	 	 ],
	["MD",			"VB",			"->",		"AUX"	 	 ],
	["NP",			"VB",			"->",		"NSUBJ"	 	 ],
	["NP",			"WDT",			"->",		"RELCL",	1],
	["WDT",			"VP",			"->",		"NSUBJ", 	2],
	["WDT",			"VB",			"->",		"NSUBJ", 	2],
];